### ISSUE TITLE
Ajout de champs

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-transitaires#1]
- [ ] ~lat et long (geojson)~
- [ ] ~url_gmaps (super pratique sur les devices mobiles)~
- [ ] ~logo stocké en dur~
- [ ] ~url vers logo sur web~
- [ ] ~vcard~
- [ ] ~qrcode contenant une vcard ou microcard~
- [x] numero RIDET aka `rid7` affin de faire le lien avec l'[open data](https://data.gouv.nc/explore/dataset/entreprises-actives-au-ridet)
- [ ] ~Structure qui détailler les jours/heures d'ouverture~
- [ ] url web ou page FB

Exemple pour GEODIS : `0046706`

**Comment by Dougniel** [comment]
👉🏼 J'ai pu récupérer 11 numéros rides sur 24 sur la base du CSV de l'Insee mais parfois aussi sur les sites internet lorsqu'ils fonctionnent

**Comment by adriens** [comment]
> 👉🏼 J'ai pu récupérer 11 numéros rides sur 24 sur la base du CSV de l'Insee mais parfois aussi sur les sites internet lorsqu'ils fonctionnent

Super, merci @Dougniel :pray:

**Comment by adriens** [comment]
je viens de tester en mode runner.... oula c violent la vitesse :point_down: 

![image](https://user-images.githubusercontent.com/5235127/179957558-fbfb2c32-7a00-466e-a0dd-0da2a9d5a06b.png)

**Comment by Dougniel** [comment]
> je viens de tester en mode runner.... oula c violent la vitesse 👇
> 
> ![image](https://user-images.githubusercontent.com/5235127/179957558-fbfb2c32-7a00-466e-a0dd-0da2a9d5a06b.png)

On est tellement habitué à du Spring que le fait que ce soit rapide impressionne. C'est pas que Quarkus soit rapide, c'est juste qu'il n'est pas lent 😅. Ce qu'on voit ici c'est du Java de base sans fioritures et ils arrivent à la même chose avec Micronaut

**Comment by adriens** [comment]
je vais voir avec @davidmajorel si il serait ok pour déployer des binaires natifs au lieu d'un `java -jar`

**Comment by Dougniel** [comment]
> je vais voir avec @davidmajorel si il serait ok pour déployer des binaires natifs au lieu d'un `java -jar`

Tu veux dire pour nos applis OPT ?

**Comment by adriens** [comment]
yep.
Car on va gentiment basculer tous os builds de proxy sur Quarkus. Vous avancez bien dans l'appropriation de Quarkus. La CI est au rdv, donc on va y aller gentiment.

En revanche : 

☝️ Pas de binaire natif : on livera que des images...c'était le but de ma démarche. on est désormais fixés @Dougniel  @pluaki. Et c'est une très bonne 🎯

**Comment by Dougniel** [comment]
> ☝️ Pas de binaire natif : on livera que des images...c'était le but de ma démarche. on est désormais fixés @Dougniel @pluaki. Et c'est une très bonne 🎯

Tu vas demander à David s'il est OK pour déployer images Docker c'est ça ?
