### ISSUE TITLE
Add emojis to ReleaseNote

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-transitaires#12]
![image](https://user-images.githubusercontent.com/5235127/177214187-85381267-f550-469a-85fe-5132b1debb30.png)

**Comment by Dougniel** [comment]
@adriens, pas sûr de comprendre, à quel niveau, un exemple ?

**Comment by adriens** [comment]
Comme ici : https://github.com/opt-nc/phonenumber-validator/releases/tag/v1.2.3

![image](https://user-images.githubusercontent.com/5235127/181104558-ef7a2c2c-590e-44c2-bcad-b893e6a19d05.png)

**Comment by adriens** [comment]
Pour info https://github.com/opt-nc/phonenumber-validator/issues/60

**Comment by Dougniel** [comment]
Ok, mais ça fait un sacré gros copié collé juste pour avoir des emojis : https://github.com/opt-nc/phonenumber-validator/commit/91bba0539b7fb45d73bce3f9ace09e711f82a99d

**Comment by Dougniel** [comment]
https://github.com/opt-nc/katacoda-opt-labs/issues/52#issuecomment-1194616320

**Comment by Dougniel** [comment]
Finalement, j'ai fait un copier/coller du pavé de 50 lignes de conf puisque https://github.com/momocow/semantic-release-gitmoji ne semble pas répondre à ce besoin

**Comment by adriens** [comment]
:+1:

**Comment by Dougniel** [comment]
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/39691264/181454698-6eabf693-1763-4e70-9123-008399c6ad53.png">

**Comment by Dougniel** [comment]
C'est liée à ce ticket https://github.com/conventional-changelog/commitlint/issues/847

**Comment by Dougniel** [comment]
Contournement appliqué

**Comment by adriens** [comment]
:sunglasses: 
![image](https://user-images.githubusercontent.com/5235127/181472796-c04c2962-c207-4ac3-b07b-5940bdbae862.png)
