### ISSUE TITLE
Scénario quickstart sur Killercoda

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-transitaires#2]

**Comment by adriens** [comment]
Feedbacks apportés, scénario en cours de finalisation.

**Comment by Dougniel** [comment]
ça commence à devenir un joyeux bordel nos tickets en double dans tous les sens : https://github.com/opt-nc/katacoda-opt-labs/issues/52

**Comment by adriens** [comment]
LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOL oui, on va améliorer ça XPTDRRR

**Comment by adriens** [comment]
Duplicate of https://github.com/opt-nc/katacoda-opt-labs/issues/52
