### ISSUE TITLE
:bug:  Typo "Transitare" au lieu de transitaire

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-transitaires#22]
![image](https://user-images.githubusercontent.com/5235127/180077493-a0d0a8c5-0443-448e-9ab0-da67e893f6c9.png)

**Comment by Dougniel** [comment]
> ![image](https://user-images.githubusercontent.com/5235127/180077493-a0d0a8c5-0443-448e-9ab0-da67e893f6c9.png)

c'était en anglais :trollface: 🏆

**Comment by adriens** [comment]
C'était pas de l 🇮🇹 ❔ 🍝
