### ISSUE TITLE
Ajouter code_officiel_geographique

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-transitaires#34]
... afiin de permettre de potenitelles jointures vers des jeux de données tiers , par exemple : 

- [Communes de la Nouvelle-Calédonie ](https://data.gouv.nc/explore/dataset/communes-nc/information/)
- [Communes de la Nouvelle-Calédonie (limites communales terrestres simplifiées) ](https://data.gouv.nc/explore/dataset/communes-nc-limites-terrestres-simplifiees/information/)

**Comment by Dougniel** [comment]
> ... afiin de permettre de potenitelles jointures vers des jeux de données tiers , par exemple :
> 
> * [Communes de la Nouvelle-Calédonie ](https://data.gouv.nc/explore/dataset/communes-nc/information/)
> * [Communes de la Nouvelle-Calédonie (limites communales terrestres simplifiées)](https://data.gouv.nc/explore/dataset/communes-nc-limites-terrestres-simplifiees/information/)

@adriens, pourquoi ne pas utiliser le code postal qui serait à la fois pratique pour un utilisateur lambda (car il peut servir au niveau postal) et aussi récupérer éventuellement d'autres choses via les services de tes examples ?

**Comment by adriens** [comment]
> [@adriens](https://github.com/adriens), pourquoi ne pas utiliser le code postal qui serait à la fois pratique pour un utilisateur lambda (car il peut servir au niveau postal) et aussi récupérer éventuellement d'autres choses via les services de tes examples ?

Yep, feu :potato: :smile_cat:

**Comment by Dougniel** [comment]
👉🏼 `codePostal` ajouté. 

⚠️ Les données sont incomplètes et pas fiables vue qu'elles vienne d'une recherche google de ma part 😉

**Comment by adriens** [comment]
Yep, je les vois 
![image](https://user-images.githubusercontent.com/5235127/181472600-034b883a-d89f-4356-b51f-5327161b4681.png)
