### ISSUE TITLE
Renvoyer id en premier

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-transitaires#35]
Actuellement on renvoie ceci : 

```json
{
        "email": "paclog@paclog.nc",
        "id": "PACLOG_PACIFIC_LOGISTICS",
        "name": "PACLOG - Pacific Logistics",
        "phone": "28.12.10",
        "ridet": "0575787",
        "website": "www.paclog.nc"
}
```

Revnoyer la clé en premier : 

```json
{
        "id": "PACLOG_PACIFIC_LOGISTICS",
        "email": "paclog@paclog.nc",
        "name": "PACLOG - Pacific Logistics",
        "phone": "28.12.10",
        "ridet": "0575787",
        "website": "www.paclog.nc"
}
```

**Comment by Dougniel** [comment]
@adriens, pour info j'ai perdu beaucoup de temps parce que `httpie` trie les champs en sortie par défaut, pour ne pas qu'il le fasse il faut faire un `http --unsorted ...'

**Comment by adriens** [comment]
Intéressant ça.

:point_up: Noter que parfois, sur des domaines très contraints et spécifiques on nous demande de respecter l'ordre. Rapproche toi de moi lors du prochain  SCRUM si tu veux en savoir davantage à ce sujet.

**Comment by Dougniel** [comment]
> Intéressant ça.
> 
> ☝️ Noter que parfois, sur des domaines très contraints et spécifiques on nous demande de respecter l'ordre. Rapproche toi de moi lors du prochain SCRUM si tu veux en savoir davantage à ce sujet.

Oui ça a du sens pour moi au niveau visibilité et je ne comprends pas le choix de `httpie` d'avoir ce comportement par défaut

**Comment by adriens** [comment]
>  et je ne comprends pas le choix de httpie d'avoir ce comportement par défaut

très bonne question : fais leur une [issue](https://github.com/httpie/httpie/issues), on saura :pray:

**Comment by adriens** [comment]
Faut customier la requête `http` du scénario alors ...
![image](https://user-images.githubusercontent.com/5235127/181472468-81c05b31-c320-4963-8f6b-65a001a55420.png)
