### ISSUE TITLE
:iphone: Ajout Qrcode avec VCard au front

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-transitaires#40]
# :grey_question: Contexte

Actuellement le front minimal est déja bien pratique, mais pour un utilisateur qui souhaite rapidement contacter le transitaire ou prendre son contact pour plus tard, il serait très pratique de pouvoir copier le contact dans son carnet d'adresse.

:point_right:  L'objectif de ce ticket est d'adresser cela

# :dart: Objectif

Sur le front... peut-être à gauche de chaque transitaire, afficher le Qrcode avec comme contenu la  [VCard](https://en.wikipedia.org/wiki/VCard) de ce dernier.

# :balance_scale:  Implémentations possibles : 

- Endpoint qui calcule le contenu du QrCode et renvoie l'image du QrCode (`base64` par exemple ?)
- Côté front
- Hybride : on calcule le contenu texte de la vCard côté back et la génération du QrCode est fait côté Front

:heavy_check_mark: Avantage/inconvénient côté back : super facile pour les devs de front... mais pollution du back
:heavy_check_mark: Avantage/inconvénient côté front : Back super clean... mais taff reporté sur les intégrateurs de front
:heavy_check_mark: Avantage/inconvénient hybride : Back toujours clean... taff côté front très limité

**Comment by adriens** [comment]
Où est le QrCode ?

![image](https://user-images.githubusercontent.com/5235127/182696279-9de73c11-fa69-40bd-a738-47083222df45.png)

![image](https://user-images.githubusercontent.com/5235127/182696359-ab8adc0d-5269-45e9-89f9-5dc5c3565238.png)

**Comment by Dougniel** [comment]
Visiblement mon message n'est pas passé sur GitHub, je disais donc : 
- pour la vCard, généré côté back car c'est une autre représentation de la même donnée
- pour le QRCode, j'ai voulu le faire côté back mais j'ai eu des soucis (ça passait pas en natif), du coup je l'ai fait côté front, en JS

<img width="580" alt="image" src="https://user-images.githubusercontent.com/39691264/182761567-2a77fcdd-0649-408a-9009-cb0b10beb3cd.png">

**Comment by adriens** [comment]
Mais je le vois pas côté front  : tu as releasé ?

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/182762777-58ad85c2-3554-4f0a-b04f-7dce2f2a00c6.png)

**Comment by adriens** [comment]
OK c'est good, faut cliquer en fait

![image](https://user-images.githubusercontent.com/5235127/182762911-fe8e3a28-6a62-45e4-aade-1fd87d37809f.png)
