### ISSUE TITLE
🚨 rapidAPI et les caractères interdits 💀 

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-transitaires#46]
![image](https://user-images.githubusercontent.com/5235127/183809331-43e79599-7484-4f3b-b866-0b493ab75f3b.png)

Remplacer 

```
{id}.vcf
```

par 

```
{id}/vcf
```

👉 **Et modifier le killercoda en conséquence** 👈

**Comment by Dougniel** [comment]
Ah RapidAPI 💩

**Comment by adriens** [comment]
Du cuop, dès que tu as fixé, je vais demander un redéploiement :trollface:  pour finalser le rapidAPI https://rapidapi.com/opt-nc-opt-nc-default/api/transitaires/

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/183839614-baf4da66-31d7-47aa-80ff-c897264ed164.png)
 C'est all :ok_hand: 

Je ferai le Jira de redeploy demain

**Comment by adriens** [comment]
Demande de redéploiement en cours cf #48
