### ISSUE TITLE
:bug:  Badge gh-pages :point_right: 404

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-transitaires#50]
Actuellement sur `main`

Sympa le badge 
![image](https://user-images.githubusercontent.com/5235127/184240521-d4b49008-4c1a-4452-90e6-c9a3f1f26ea3.png)
 mais attention, ça pointe actuellement vers une `404`
![image](https://user-images.githubusercontent.com/5235127/184240581-0126bce4-f485-4853-80aa-7e97054161f2.png)

**Comment by Dougniel** [comment]
https://github.com/opt-nc/api-transitaires/issues/9#issuecomment-1211693616

**Comment by adriens** [comment]
> Je vais enlever ce lien en attendant que ça fonctionne

:+1:

**Comment by adriens** [comment]
:ok_hand:

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/184988750-c8f9b97b-53d2-43e1-9f96-5500c560848f.png)
