### ISSUE TITLE
 :link: Compléter le "About" avec url redocly

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-transitaires#51]
![image](https://user-images.githubusercontent.com/5235127/184241064-be8373e4-90a9-4d42-9b05-f59b81fdbf2c.png)

**Comment by Dougniel** [comment]
Je le ferais dès que ça marchera 
#50 
#9 

@adriens, pour réduire la charge sur la gestion des issues, ne pourraient-ton pas mettre tous ces points qui concernent Redocly au sein du même ticket initial, le #9 ?

**Comment by adriens** [comment]
> ne pourraient-ton pas mettre tous ces points qui concernent Redocly au sein du même ticket initial,

Of course :+1:

**Comment by Dougniel** [comment]
OK, j'ai remplacé l'ancienne URL

**Comment by adriens** [comment]
:ok_hand: 
![image](https://user-images.githubusercontent.com/5235127/184989018-a9c367a4-1a7a-4a90-ad6f-e359c3adb74a.png)
