### ISSUE TITLE
Ajouter .sdkmanrc

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-transitaires#52]

**Comment by Dougniel** [comment]
@adriens, je ne suis pas sûr que ceci nous aide car : 

- dependabot ne fera pas d'upgrade - ce sera le rare truc à ne pas être upgradé
- une version aura beau être spécifié, la CI ne l'utilisera pas, elle utilisera celle spécifiée dans le workflow

En plus de cela, je vois mal la valeur ajouté vu qu'a termes on va tout passer en Java 17, c'est la cible non ?

**Comment by adriens** [comment]
C'est pour les dévelopeurs, pour que l'env de dev switche automatiquement cf https://dev.to/optnc/java-runtime-management-automation-with-sdkman-sdkmanrc-3eoi


> dependabot ne fera pas d'upgrade - ce sera le rare truc à ne pas être upgradé

je ne vois pas le rapport

> une version aura beau être spécifié, la CI ne l'utilisera pas, elle utilisera celle spécifiée dans le workflow

Prendre en compte ce qui a été dit en scrum...

> En plus de cela, je vois mal la valeur ajouté vu qu'a termes on va tout passer en Java 17, c'est la cible non ?

Les développeurs jonglent au quotidien entre java 8, 17, prochainement 18 ou 19, etc... je souhate que l'env de dev soit spécifié

**Comment by adriens** [comment]
cf tuto https://killercoda.com/opt-labs/course/sdkman/sdkmanrc

**Comment by Dougniel** [comment]
J'ai fait du feedback, peut-être tardivement mais je n'avais pas eu l'occasion de me pencher sur ce sujet auparavant. Mon approche, c'est la recherche de l'efficacité par la suppression notamment du superflu - _Keep It Simple_ - pour moi c'est superflu, mais si je suis le seul à le penser c'est qu'au niveau groupe il faut rester la dessus

👉🏼 J'ai repris la même conf que [api-phonenumber-validator](https://github.com/opt-nc/api-phonenumber-validator/blob/main/.sdkmanrc)

**Comment by adriens** [comment]
Super, merci @Dougniel , ainsi les devs pourront tourner confortablement d'un porjet à un autre.
On gagne de la metadata pour la carographie également.

**Comment by mbarre** [comment]
Hello @Dougniel ,

Je trouvais cela superflu aussi au départ, mais je l'ai spécifié sur plusieurs de mes projets dont les runtimes n'etaient pas les mêmes. Au final je trouve cela pratique de ne pas avoir à passer la commande sdk moi même (et à devoir y penser) pour switcher de version de java.

**Comment by adriens** [comment]
Ouij'ai été spectateur de ça la semaine dernière.

Après on peut discuter du maven enforcer qui est un autre sujet...

**Comment by Dougniel** [comment]
> Super, merci @Dougniel , ainsi les devs pourront tourner confortablement d'un porjet à un autre.
> On gagne de la metadata pour la carographie également.

Et de le récupérer plutôt depuis Maven ? N'est-ce pas là la référence ?

> Je trouvais cela superflu aussi au départ, mais je l'ai spécifié sur plusieurs de mes projets dont les runtimes n'etaient pas les mêmes. Au final je trouve cela pratique de ne pas avoir à passer la commande sdk moi même (et à devoir y penser) pour switcher de version de java.

Ok, merci pour ce retour @mbarre. De mon côté j'ai tendance à passer par mon IDE pour lancer une appli de dev, c'est peut-être pour ça que j'y trouve moins d'intérêt

**Comment by adriens** [comment]
> Et de le récupérer plutôt depuis Maven ? N'est-ce pas là la référence ?

Oui, on fera ce choix probablement lors de la task dédiée aux repox GH pour carto cf https://github.com/opt-nc/carto-neo4j/issues/70
