### ISSUE TITLE
:bug:  Shield Docker stars broken (invalid) :whale2: 

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-transitaires#58]
# :grey_question: Description

![image](https://user-images.githubusercontent.com/5235127/184983668-291cc6f9-dde4-44ec-b92a-0cec841ac4ca.png)

![image](https://user-images.githubusercontent.com/5235127/184983973-d013edaa-b458-41e8-ace5-1518c762e6d4.png)

**Comment by adriens** [comment]
Bug reported see https://github.com/badges/shields/issues/8314

**Comment by adriens** [comment]
Things on the way to ve fixed @Dougniel  @mbarre @spencer-forrest-opt @pluaki  : 

![image](https://user-images.githubusercontent.com/5235127/185240779-bf5a7e3e-a0d2-4bd1-bd95-6b661955ba2f.png)

https://github.com/badges/shields/issues/8314#issuecomment-1218316750

**Comment by adriens** [comment]
Voila https://github.com/badges/shields/issues/8314#issuecomment-1219870518

**Comment by adriens** [comment]
Fixé !
![image](https://user-images.githubusercontent.com/5235127/185491362-8a84f8f7-1e97-4150-b993-ce7be332ffbc.png)

**Comment by Dougniel** [comment]
> Fixé !
> ![image](https://user-images.githubusercontent.com/5235127/185491362-8a84f8f7-1e97-4150-b993-ce7be332ffbc.png)

Alors là bravo !

**Comment by adriens** [comment]
> Alors là bravo !

Merci @Dougniel , ça fait super plaisir :heavy_heart_exclamation: Et puis la satisaction d'avoir participé au fix pour tout le monde, ça fait bien plaisir, c'est très satisfaisant.... comme quoi, bien connaître nos outils n'est jamais... jamais une perte de temps.
 cf https://dev.to/optnc/show-me-your-dockerhub-public-images-in-your-terminal-39n4
