### ISSUE TITLE
🙈 Ecart dans la version de la doc redocly et de la release

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/api-transitaires#68]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/39691264/190350225-1d14dbdc-7e6c-4e76-bfda-11ad5e1feb8d.png">

<img width="630" alt="image" src="https://user-images.githubusercontent.com/39691264/190350305-d72226dc-1564-45f6-81f9-0b7e6e0ca7b7.png">

**Comment by adriens** [comment]
:hankey: :sweat_smile:
