### ISSUE TITLE
Front-end minimaliste

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-transitaires#7]

**Comment by Dougniel** [comment]
@adriens, là tu m'as paumé : pourquoi une 3éme issue pour le front de api-transitaires ?

ça me semble être identique : https://github.com/opt-nc/GLIA/issues/706#issuecomment-1172765394

**Comment by adriens** [comment]
Dans le cas om quelqu'un veut d'entrainer a construire une image dédiée cliente

**Comment by Dougniel** [comment]
Duplicate of https://github.com/opt-nc/GLIA/issues/695

**Comment by adriens** [comment]
👍

**Comment by adriens** [comment]
Tu peux mettre à jour l'url dans `README.md` :pray: 

![image](https://user-images.githubusercontent.com/5235127/177215078-e314f6a0-cad0-4417-89b4-447dd0cf7d60.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/177253071-29b39209-c7b6-41e0-a242-a7c081f26563.png)

**Comment by adriens** [comment]
Tu peux ajouter le lien dans la doc du `README`stp ?

**Comment by Dougniel** [comment]
@adriens, cette anno est en double c'est pour cela qu'elle était fermée : 
<img width="586" alt="image" src="https://user-images.githubusercontent.com/39691264/177253609-cd7cc0a2-c8f8-4339-9689-378ddc9da062.png">

Concernant la modification je l'ai fait sur la branche dev 👍

**Comment by adriens** [comment]
Ok, j'attends le merge sur `main` alors
