### ISSUE TITLE
Site promotionnel> redocly

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-transitaires#9]
~Via revealjs/gh-pages ?~

- [ ] Faire fonctionner
- [x] https://github.com/opt-nc/api-transitaires/issues/50
- [ ] https://github.com/opt-nc/api-transitaires/issues/51

**Comment by adriens** [comment]
mise en avant de ce que permet l'api, etc....

Video démo, aexemples d'appels api, qrcode killercoda, image docker,... un slide par contenu

**Comment by Dougniel** [comment]
> Video démo, aexemples d'appels api, qrcode killercoda, image docker,... un slide par contenu

@adriens, de l'eau à coulé sur les ponts depuis, un tas de chose a été faite alors j'ai considéré que ce ticket ne concerne que  redocly, dis-moi si ça te va stp

@adriens, @mbarre 

Je me suis rendu compte d'une incohérence dans la CI avec redocly : lorsqu'on fait un commit qui ne concerne que de la doc, on utilise la forme de message de commit `docs(<scope>): <message>` pour respecter la convention semantique des commits. Or de cette manière, semantic-release ne déclenche pas de release, donc les githubpages ne sont pas mise à jour avec les éventuels changements vu que la génération redocly se déclenche lors d'une release (ce qui a du sens vu que dans les githubpages on n'a qu'une seule "branche", on ne peut pas se contenter de déclencher à chaque push)... Que fais-ton ?

**Comment by Dougniel** [comment]
Je ne sais pas ce qui se passe, mais le workflow ne se lance pas sans rien dire. Encore un bug GitHub

ça a marché du premier coup lorsque je l'ai mis en place sur proxy-docubase en faisant un simple copie-coller

j'ai essayé par l'écran de settings > GitHub pages est c'est pareil, même en forçant une nouvelle release. Je pige pas, des idées @mbarre ?

**Comment by mbarre** [comment]
@adriens, 

tu pourrais me mettre admin de la repo stp ? j'ai besoin de voir la configuration des branches .

Merci

**Comment by adriens** [comment]
Yep @mbarre , voila qui est fait : 
![image](https://user-images.githubusercontent.com/5235127/184023161-4613d0ee-2bae-4ca6-b01e-a3657c580d48.png)

**Comment by mbarre** [comment]
> Or de cette manière, semantic-release ne déclenche pas de release, donc les githubpages ne sont pas mise à jour avec les éventuels changements vu que la génération redocly se déclenche lors d'une release (ce qui a du sens vu que dans les githubpages on n'a qu'une seule "branche", on ne peut pas se contenter de déclencher à chaque push)... Que fais-ton ?

Je suis partie du principe qu'en général (sauf 1er déploiement) si on modifie la doc c'est : 
- qu'on a fait des modifications dans la signature des methodes exposées
- supprimé des endpooints
- ajouté des endpoints
Dans ces 3 cas, on déclenche une release et la doc est mise a jour. Cela me paraissait suffisant, je ne voyais pas l'interet de mettre a jour la doc de l'api à chaque push et de consommer du temps de CI. 

Cela nous contraint aussi a bien penser à mettre la doc à jour avant de faire un release.

Dites moi si vous pensez que c'est trop contraignant, on passe au `push`

**Comment by mbarre** [comment]
J'ai modifié la regle de deploiement sur l'environnement `github-pages`

Le deploiement n'etait autorisé que sur la branche `main`, je l'ai passé à `v*.*.*`

![image](https://user-images.githubusercontent.com/1823161/184025024-d039bb31-1bdb-418a-ae83-d365d31afab0.png)

**Comment by adriens** [comment]
@Dougniel : 

>  Encore un bug GitHub

... :thinking:

**Comment by mbarre** [comment]
Si tu veux deployer la doc, tu peux supprimer la release et le tag `v1.3.3` et relancer le dernier job `test-release`. C'est pas joli-joli mais c'est efficace si tu as pas de feature ou de fix a pousser. Ca evite de faire une release pour fix bidon....

Je te laisse choisir :smile:

**Comment by adriens** [comment]
:rofl:

**Comment by adriens** [comment]
@mbarre 
> Dites moi si vous pensez que c'est trop contraignant, on passe au push

On peut en parler en SCRUM tout à l'heure avec @Dougniel et @spencer-forrest-opt

**Comment by Dougniel** [comment]
> Si tu veux deployer la doc, tu peux supprimer la release et le tag `v1.3.3` et relancer le dernier job `test-release`. C'est pas joli-joli mais c'est efficace si tu as pas de feature ou de fix a pousser. Ca evite de faire une release pour fix bidon....
> 
> Je te laisse choisir 😄

Oui la suppression du tag pour faire une relance c'est aussi ce que je choisis de faire pour les mêmes raisons

Merci pour ta correction ! 

> Je suis partie du principe qu'en général (sauf 1er déploiement) si on modifie la doc c'est :
> 
> * qu'on a fait des modifications dans la signature des methodes exposées
> * supprimé des endpooints
> * ajouté des endpoints
>   Dans ces 3 cas, on déclenche une release et la doc est mise a jour. Cela me paraissait suffisant, je ne voyais pas l'interet de mettre a jour la doc de l'api à chaque push et de consommer du temps de CI.
> 
> Cela nous contraint aussi a bien penser à mettre la doc à jour avant de faire un release.
> 
> Dites moi si vous pensez que c'est trop contraignant, on passe au `push`

Je pense que c'est généralement le cas, mais c'est trop restrictif : la correction d'une faute d'orthographe ou la mise à jour pour ajouter de la doc à un endpoint nous fera faire des cabrioles. S'il n'y a pas d'autres contraintes, je suis pour le mode `push` sur la branche `main` (par la même occasion on n'aura plus cette rectification à faire, si j'ai bien compris)

**Comment by Dougniel** [comment]
Bon, en relançant j'ai toujours eu le même soucis car : 

- Le token utilisé GH utilisé par la sementic-release qui crée la release était `GITHUB_TOKEN` vu que c'est un projet public (je ne peux utiliser `OPT_CI_TOKEN`)
- par conséquent pas de déclenchement d'un autre workflow

👉🏼 il me semble plus simple de ne pas déclencher un autre workflow car sinon ça nous fait crée d'autres TOKEN en mode public et je sais, je vais essayer de l'intégrer au workflow de build, au passage sans nécessite de release, mais sur la branche `main`

@mbarre, @adriens dites moi si ça vous va

**Comment by adriens** [comment]
https://github.com/opt-nc/api-transitaires/issues/50

**Comment by adriens** [comment]
>  crée d'autres TOKEN en mode public 

Oui, créer en mode public a pas mal d'inconvénients...

**Comment by mbarre** [comment]
Ha mince... c'est vrai, mon projet est privé du coup j'ai pu utiliser les tokens...
Ben oe pas le choix du coup, reste que le declenchement sur le push...

**Comment by adriens** [comment]
Comme quoi, tojours bien d'avoir des petits porjets bien divers
